In [2]:
import numpy as np

In [3]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
arr[5]

np.int64(5)

In [5]:
arr[2:6]

array([2, 3, 4, 5])

In [26]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr1[1,1]

np.int64(4)

In [16]:
arr1[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
arr1[:2,:2]

array([[0, 1],
       [3, 4]])

In [22]:
arr1[1,:2]

array([3, 4])

In [28]:
arr1[1,:2]

array([3, 4])

In [30]:
bo = np.array([1,0,1], dtype=bool)
bo

array([ True, False,  True])

In [34]:
print(arr1[bo, 1])

[1 7]


In [35]:
arr2 = np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# 将数组扁平化，即将原本可能是二维、三维甚至更高维度的数组，拉伸成一条线，变成一个一维数组
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
arr3 = arr2*2
arr3

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [ ]:
# 水平堆叠 = 左右拼接。它的作用是将数组在水平方向（按列）顺序拼接。
np.hstack((arr2,arr3))

array([[ 0,  1,  2,  3,  4,  0,  2,  4,  6,  8],
       [ 5,  6,  7,  8,  9, 10, 12, 14, 16, 18],
       [10, 11, 12, 13, 14, 20, 22, 24, 26, 28],
       [15, 16, 17, 18, 19, 30, 32, 34, 36, 38]])

In [44]:
# 垂直堆叠 = 上下拼接。它的作用是将数组在垂直方向（按行）顺序拼接。
np.vstack((arr2,arr3))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [ ]:
# 水平分割 = 左右切（按列切）。它的作用是将数组在水平方向切分成若干份。
np.hsplit(arr3,5)

[array([[ 0],
        [10],
        [20],
        [30]]),
 array([[ 2],
        [12],
        [22],
        [32]]),
 array([[ 4],
        [14],
        [24],
        [34]]),
 array([[ 6],
        [16],
        [26],
        [36]]),
 array([[ 8],
        [18],
        [28],
        [38]])]

In [ ]:
# 垂直分割 = 上下切（按行切）。它的作用是将数组在垂直方向切分成若干份。
np.vsplit(arr3,4)

[array([[0, 2, 4, 6, 8]]),
 array([[10, 12, 14, 16, 18]]),
 array([[20, 22, 24, 26, 28]]),
 array([[30, 32, 34, 36, 38]])]

In [ ]:
# 数组的转置。简单来说，就是把数组的行和列互换，就像矩阵转置一样
arr3.transpose()

array([[ 0, 10, 20, 30],
       [ 2, 12, 22, 32],
       [ 4, 14, 24, 34],
       [ 6, 16, 26, 36],
       [ 8, 18, 28, 38]])

In [55]:
arr4 = np.arange(12).reshape(3,4)
arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
# 交换数组的两个指定轴（维度）。代表第 0 个轴（通常指行）。1：代表第 1 个轴（通常指列）。
# 就是把第 0 轴和第 1 轴的位置互换。
arr5 = arr4.swapaxes(0,1)
arr5

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [60]:
arr4.shape

(3, 4)

In [66]:
arr5.shape

(4, 3)

In [69]:
arr5 = np.arange(40).reshape(5,2,4)
arr5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [70]:
arr6 = arr5.swapaxes(0,1)
arr6

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27],
        [32, 33, 34, 35]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [36, 37, 38, 39]]])