In [1]:
import numpy as np

In [7]:
a = np.array([1,2,3,4,5])

In [8]:
a.dtype.name

'int64'

In [15]:
arr = np.array(['pandas', 'numpy', 'tensorflow', 'scipy'])
arr

array(['pandas', 'numpy', 'tensorflow', 'scipy'], dtype='<U10')

In [18]:
b = np.array([[1,2,3],[4,5,6]])
b
b.dtype

dtype('int64')

In [32]:
# 将数组 b 的数据类型转换为 float64（双精度浮点数），并将结果赋值给新变量 new_b
new_b = b.astype('float64')
print(new_b.dtype)
b.dtype

float64


dtype('int64')

In [35]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b = np.array([[7,8,9],[10,11,12]])
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [39]:
a * b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [40]:
c = np.array([3,4,5])

In [41]:
a * c

array([[ 3,  8, 15],
       [12, 20, 30]])

In [42]:
print(a.shape)
print(c.shape)

(2, 3)
(3,)


In [44]:
d = 20
a * d

array([[ 20,  40,  60],
       [ 80, 100, 120]])