In [3]:
import numpy as np

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((2,3))

In [ ]:
np.ones([3,4])

In [ ]:
np.diag([1,2,3,4])

In [ ]:
np.eye(4)

In [7]:
np.empty((5,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.33511018e-306],
       [9.34600284e-307, 1.42413555e-306],
       [1.78019082e-306, 1.37959740e-306],
       [6.23057349e-307, 1.42419530e-306]])

In [8]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [10]:
np.arange(2,8,2)

array([2, 4, 6])

In [ ]:
# 在指定的区间（这里是 1 到 2）内，生成固定数量（这里是 6 个）的等间距数列
np.linspace(1,2,6)
# 将区间 [1, 2] 分成 6 - 1 = 5 个等长的间隔。步长 = (2 - 1) / 5 = 0.2。生成的序列为：1.0, 1.2, 1.4, 1.6, 1.8, 2.0

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

`np.logspace(0, 2, 8)` 的作用是：**生成一个等比数列**。

具体来说，它生成 8 个数字，这些数字以 10 为底数，指数范围从 $10^0$ 到 $10^2$（即从 1 到 100），并且在对数尺度上是均匀分布的。


`np.logspace` 常用于：
1.  **创建频率轴**：在信号处理或声学中，人耳对声音的感知是呈对数关系的（如倍频程），因此频率通常使用对数坐标。
2.  **科学绘图**：当数据的跨度非常大（例如从 0.01 到 1000）时，使用线性坐标会让小数值看不清，此时需要在对数坐标下绘图，`np.logspace` 非常适合生成这种坐标轴数据。

### 类比理解

你可以把它理解为 `np.linspace` 的“指数版”：

*   **`np.linspace(1, 100, 8)`**: 生成的数字是**相加**递增的（1, 15, 29...）。
*   **`np.logspace(0, 2, 8)`**: 生成的数字是**相乘**递增的（1, 1.9, 3.7...）。

In [ ]:

np.logspace(0,2,8)

array([  1.        ,   1.93069773,   3.72759372,   7.19685673,
        13.89495494,  26.82695795,  51.79474679, 100.        ])

In [ ]:
"""从指定的整数范围内（半开区间），随机抽取整数生成一个指定形状的数组
low (下限): 起始整数（包含）。这里是 100。
high (上限): 结束整数（不包含）。这里是 200。
这意味着生成的数字范围是 [100,200)，即：最小是 100，最大是 199，不会生成 200。
size (形状): 输出数组的维度。这里是 (2, 4)，表示生成一个 2行 4列 的二维数组。
"""
np.random.randint(100,200,size=(2,4))

array([[159, 175, 103, 116],
       [151, 122, 162, 126]], dtype=int32)

In [180]:
# 生成一个给定形状的数组，其中的数值来自于“标准正态分布”在 [0.0, 1.0) 之间的均匀分布随机浮点数。
# 简单来说，它就是生成一个 2行 4列 的矩阵，里面的数字都是 0 到 1 之间的小数。
np.random.rand(2,4)

array([[0.8811209 , 0.31682174, 0.92039191, 0.82011513],
       [0.54325854, 0.11413791, 0.32757577, 0.38481198]])