In [1]:
import numpy as np

In [2]:
# 三元运算符案例
arr_x = np.array([1, 4, 5])
arr_y = np.array([2, 6, 7])
arr_con = np.array([True, False, False])

索引 (Index),arr_con (条件),arr_x (若真),arr_y (若假),结果 (Result)
0,True,1,2,1
1,False,4,6,6
2,False,5,7,7

In [3]:
# 根据条件选择：如果为 True 选 arr_x，为 False 选 arr_y
np.where(arr_con, arr_x, arr_y)
# 输出: array([1, 6, 7])

array([1, 6, 7])

In [4]:
# 使用数值判断作为条件
np.where(arr_x > 3, 1, 0)
# 输出: array([0, 1, 1])

array([0, 1, 1])

In [6]:
# 求和运算
np.sum(arr_x)
# 输出: 10

np.int64(10)

In [18]:
# 创建一个 2行5列 的二维数组
# np.arange(10) 生成 0-9 的序列，reshape((2, 5)) 将其重塑为矩阵
arr = np.arange(10).reshape((2, 5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
# 沿轴 1 (行方向) 求和
# axis=1 表示对每一行进行操作，得到每一行的总和
np.sum(arr, axis=1)

array([10, 35])

In [ ]:
# 沿轴 1 求平均值
np.mean(arr, axis=1)

array([2., 7.])

In [ ]:
# 沿轴 1 找出最小值
np.min(arr, axis=1)

array([0, 5])

In [ ]:
# 沿轴 1 找出最大值
np.max(arr, axis=1)

array([4, 9])

In [ ]:
# 查找全局最小值的索引
# 注意：如果不指定 axis，argmin 会将数组展开成一维，返回索引 0 (即元素 0)
np.argmin(arr)

np.int64(0)

In [ ]:
# 查找全局最大值的索引
# 元素 9 是最大值，其在一维展开后的索引是 9
np.argmax(arr)

np.int64(9)

In [ ]:
# 累加和 (Cumulative Sum)
# 将所有元素按顺序逐个累加，返回一个一维序列
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
# 累乘积 (Cumulative Product)
# 因为第一个元素是 0，所以之后所有的乘积结果都会是 0
np.cumprod(arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# 排序

In [21]:
# 创建一个 2行3列 的二维数组
arr = np.array([[6, 3, 4], [7, 5, 2]])

In [22]:
# 沿轴 0 (axis=0) 进行排序
# axis=0 代表“纵向”，即对每一列内部的元素进行排序
# 比如第一列是 [6, 7]，排序后不变
# 第二列是 [3, 5]，排序后不变
# 第三列是 [4, 2]，排序后变成 [2, 4]
arr.sort(axis=0)
arr

array([[6, 3, 2],
       [7, 5, 4]])

In [23]:
np.all(arr>2)

np.False_

In [24]:
np.any(arr>2)

np.True_

In [26]:
arr>3

array([[ True, False, False],
       [ True,  True,  True]])

# 去重和重复

In [43]:
# 创建一个含有重复元素的数组
arr = np.array([12, 11, 34, 23, 12, 8, 11])

In [28]:
# 使用 np.unique 进行去重
# 这个函数会做两件事：
# a) 剔除所有重复的数字
# b) 将结果从小到大进行排序
arr1 = np.unique(arr)
arr1

array([ 8, 11, 12, 23, 34])

In [41]:
# 这个警告信息提示你正在使用 NumPy 库中一个已经被弃用（Deprecated）的函数 np.in1d。
# NumPy 官方建议使用 np.isin 来替代它。虽然旧代码目前可能还能运行，但为了代码的长期兼容性和最佳实践，你应该进行修改
np.in1d(arr, [11,12])

C:\Users\yandifei\AppData\Local\Temp\ipykernel_41544\1025378873.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(arr, [11,12])


array([False, False, False, False, False, False])

In [44]:
# 可以使用状态
np.isin(arr, [11,12])

array([ True,  True, False, False,  True, False,  True])

In [30]:
np.tile(arr1,3)

array([ 8, 11, 12, 23, 34,  8, 11, 12, 23, 34,  8, 11, 12, 23, 34])

In [31]:
arr1

array([ 8, 11, 12, 23, 34])

In [32]:
arr1.repeat(3)

array([ 8,  8,  8, 11, 11, 11, 12, 12, 12, 23, 23, 23, 34, 34, 34])

In [33]:
arr = np.array([[6, 3, 4], [7, 5, 2]])
arr

array([[6, 3, 4],
       [7, 5, 2]])

In [35]:
arr.repeat(3, axis=0)

array([[6, 3, 4],
       [6, 3, 4],
       [6, 3, 4],
       [7, 5, 2],
       [7, 5, 2],
       [7, 5, 2]])

In [38]:
arr.repeat(3, axis=1)

array([[6, 6, 6, 3, 3, 3, 4, 4, 4],
       [7, 7, 7, 5, 5, 5, 2, 2, 2]])

# 随机模块

In [ ]:
# 生成一个 [0.0, 1.0) 之间的随机浮点数。
# 不传参数时，返回单个数值。
np.random.rand()

0.44352332144597184

In [ ]:
# 2. np.random.rand(2, 3)
# 生成一个指定形状（Shape）的数组，这里是 2行3列。
np.random.rand(2,3)

array([[0.52481426, 0.80339907, 0.2244894 ],
       [0.38115144, 0.36656155, 0.60553545]])

In [50]:
# 3. np.random.randint(1, 10)
# 在指定范围内生成随机整数。
# 参数含义：(low, high)，包含 low，但不包含 high（即左闭右开 [1, 10)）。
# 结果会是 1 到 9 之间的随机一个整数。
np.random.randint(1,10)

3