In [45]:
import numpy as np

In [46]:
# 超市牛奶价格比较
# 创建两个超市的牛奶价格数组
milk_a = np.array([19.9, 25, 29.9, 45, 39.9])
milk_b = np.array([18.9, 25, 24.9, 49, 35.9])

# 比较运算：milk_a 的价格是否大于 milk_b
milk_a > milk_b

array([ True, False,  True, False,  True])

In [47]:
# 切片与索引练习
# 2.1 创建0-24的5x5数组并索引
ar = np.arange(25).reshape(5, 5)
# 打印整个数组ar
print(ar)
# 打印数组ar中索引为4的元素
print(ar[4])
# 打印数组ar中前两行且从第三列开始到最后的所有元素
print(ar[:2, 3:])
# 打印数组ar中第四行第三列的元素
print(ar[3][2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[20 21 22 23 24]
[[3 4]
 [8 9]]
17


In [48]:
# 2.2 创建0~9的2x5数组，筛选大于5的元素
ar2 = np.arange(10).reshape(2, 5)
print(ar2)
filtered = ar2[ar2 > 5]
filtered

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([6, 7, 8, 9])

In [49]:
# 2.3创建一个10x10数组，边界为1，内部为0
boundary_array = np.zeros((10, 10))
boundary_array[0, :] = 1
boundary_array[-1, :] = 1
boundary_array[:, 0] = 1
boundary_array[:, -1] = 1
boundary_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
# 2.4 创建一个从10到49的ndarray对象，并倒序复制给另一个变量
arr = np.arange(10, 50)
arr_reversed = arr[::-1]
print(arr)
arr_reversed

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [51]:
# 2.5 交换二维数组的第二行与第三行
a = np.arange(20).reshape(4, 5)
print(a)
a[[1, 2]] = a[[2, 1]]
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [52]:
# 统计分析
"""
班里有10名同学，随机生成成绩
现在需要用numpy来统计下这些人在python、网络爬虫、大学语文中的
平均成绩、最小成绩、最大成绩、方差、标准差，进行成绩输出。
"""
# 我假设成绩是0-100分，10个学生，每个学生3门成绩就是一个10x3的数组
scores = np.random.randint(0, 100, size=(10, 3))
scores

array([[18, 88,  4],
       [93, 42, 14],
       [26, 25, 49],
       [ 6, 31, 42],
       [43, 49, 67],
       [79,  6,  9],
       [ 6, 94, 13],
       [13, 65,  5],
       [32, 80,  8],
       [39, 79, 65]], dtype=int32)

In [53]:
# 定义这个数组的数据类型
# scores_dytype = np.dtype(
#     ("Python", int),
#     ("网络爬虫", int),
#     ("大学语文", int)
# )

In [54]:
# # 将现在的类型转换为自定义的类型
# scores = scores.astype(scores_dtype)
# scores

In [55]:
# 计算每门课的统计指标
# 计算每门课程成绩的平均值，axis=0表示按列计算
mean_scores = np.mean(scores, axis=0)
# 计算每门课程成绩的最小值，axis=0表示按列计算
min_scores = np.min(scores, axis=0)
# 计算每门课程成绩的最大值，axis=0表示按列计算
max_scores = np.max(scores, axis=0)
# 计算每门课程成绩的方差，axis=0表示按
var_scores = np.var(scores, axis=0)    
# 计算每门课程成绩的标准差，axis=0表示按列计算
std_scores = np.std(scores, axis=0)

# 输出统计结果
subjects = ["Python", "网络爬虫", "大学语文"]
for i, sub in enumerate(subjects):  # 遍历每门课程及其索引
    print(f"{sub}:")  # 输出课程名称
    print(f"  平均分: {mean_scores[i]}")  # 输出平均分，保留两位小数
    print(f"  最低分: {min_scores[i]}")      # 输出最低分
    print(f"  最高分: {max_scores[i]}")      # 输出最高分
    print(f"  方差: {var_scores[i]}")    # 输出方差，保留两位小数
    print(f"  标准差: {std_scores[i]}")  # 输出标准差，保留两位小数

Python:
  平均分: 35.5
  最低分: 6
  最高分: 93
  方差: 792.25
  标准差: 28.146935890075138
网络爬虫:
  平均分: 55.9
  最低分: 6
  最高分: 94
  方差: 798.49
  标准差: 28.257565358678725
大学语文:
  平均分: 27.6
  最低分: 4
  最高分: 67
  方差: 581.24
  标准差: 24.108919511251433
