In [80]:
import numpy as np
import csv

In [92]:
# 导入必要的库（虽然代码中未显示，但使用csv.reader需要导入csv库）
# 创建一个空列表用于存储鸢尾花数据
iris_data = []
# 使用with语句打开文件，确保文件在使用后被正确关闭
# 'iris.csv'是要读取的文件名
# 'r'表示以只读模式打开文件
# encoding="gbk"指定文件编码为gbk格式
with open('iris.csv','r', encoding="gbk") as csvfile:
    # 创建CSV阅读器对象，用于逐行读取CSV文件内容
    csv_reader = csv.reader(csvfile)
    # 跳过CSV文件的标题行（第一行）
    print(csvfile.readline())
    # 遍历CSV阅读器中的每一行
    for row in csv_reader:
        # 将每一行数据转换为元组，并添加到iris_data列表中
        iris_data.append(tuple(row))
# 打印处理后的鸢尾花数据列表
print(iris_data)
# #数据清洗，将列表改成元祖，保证数据的只读性，不被篡改
# iris_list = []
# for row in iris_data:
#     iris_list.append(tuple(row))
# iris_list

花萼长度,花萼宽度,花瓣长度,花瓣宽度,种类

[('5.1', '3.5', '1.4', '0.2', 'Iris-setosa'), ('4.9', '3', '1.4', '0.2', 'Iris-setosa'), ('4.7', '3.2', '1.3', '0.2', 'Iris-setosa'), ('4.6', '3.1', '1.5', '0.2', 'Iris-setosa'), ('5', '3.6', '1.4', '0.2', 'Iris-setosa'), ('5.4', '3.9', '1.7', '0.4', 'Iris-setosa'), ('4.6', '3.4', '1.4', '0.3', 'Iris-setosa'), ('5', '3.4', '1.5', '0.2', 'Iris-setosa'), ('4.4', '2.9', '1.4', '0.2', 'Iris-setosa'), ('4.9', '3.1', '1.5', '0.1', 'Iris-setosa'), ('5.4', '3.7', '1.5', '0.2', 'Iris-setosa'), ('4.8', '3.4', '1.6', '0.2', 'Iris-setosa'), ('4.8', '3', '1.4', '0.1', 'Iris-setosa'), ('4.3', '3', '1.1', '0.1', 'Iris-setosa'), ('5.8', '4', '1.2', '0.2', 'Iris-setosa'), ('5.7', '4.4', '1.5', '0.4', 'Iris-setosa'), ('5.4', '3.9', '1.3', '0.4', 'Iris-setosa'), ('5.1', '3.5', '1.4', '0.3', 'Iris-setosa'), ('5.7', '3.8', '1.7', '0.3', 'Iris-setosa'), ('5.1', '3.8', '1.5', '0.3', 'Iris-setosa'), ('5.4', '3.4', '1.7', '0.2', 'Iris-setosa'), ('5.1', '3.7', '1.5', '0.4', 'Iris-setosa'

In [93]:
# 定义结构化数据类型，格式为np.dtype([(字段名1,类型1,长度1),(字段名2,类型2,长度2),...])，其中'<f8'表示浮点数，'<U10'表示字符串，'class'列的字符串长度为10
iris_type = np.dtype([
    ('Sepal.Length', np.str_, 40), # 字段名, 字符串类型, 最大长度40
    ('Sepal.Width',  np.str_, 40),
    ('Petal.Length', np.str_, 40),
    ('Petal.Width',  np.str_, 40),
    ('Species',      np.str_, 40)
])

In [94]:
# 普通数组像只有编号的寄存柜，存取全靠数索引；结构化数组像贴了标签的药柜，能给每列定名字和类型，存取直接喊字段名。
iris_data = np.array(iris_data,dtype=iris_type)
iris_data

array([('5.1', '3.5', '1.4', '0.2', 'Iris-setosa'),
       ('4.9', '3', '1.4', '0.2', 'Iris-setosa'),
       ('4.7', '3.2', '1.3', '0.2', 'Iris-setosa'),
       ('4.6', '3.1', '1.5', '0.2', 'Iris-setosa'),
       ('5', '3.6', '1.4', '0.2', 'Iris-setosa'),
       ('5.4', '3.9', '1.7', '0.4', 'Iris-setosa'),
       ('4.6', '3.4', '1.4', '0.3', 'Iris-setosa'),
       ('5', '3.4', '1.5', '0.2', 'Iris-setosa'),
       ('4.4', '2.9', '1.4', '0.2', 'Iris-setosa'),
       ('4.9', '3.1', '1.5', '0.1', 'Iris-setosa'),
       ('5.4', '3.7', '1.5', '0.2', 'Iris-setosa'),
       ('4.8', '3.4', '1.6', '0.2', 'Iris-setosa'),
       ('4.8', '3', '1.4', '0.1', 'Iris-setosa'),
       ('4.3', '3', '1.1', '0.1', 'Iris-setosa'),
       ('5.8', '4', '1.2', '0.2', 'Iris-setosa'),
       ('5.7', '4.4', '1.5', '0.4', 'Iris-setosa'),
       ('5.4', '3.9', '1.3', '0.4', 'Iris-setosa'),
       ('5.1', '3.5', '1.4', '0.3', 'Iris-setosa'),
       ('5.7', '3.8', '1.7', '0.3', 'Iris-setosa'),
       ('5.1', '3.8', '1

In [95]:
Sepal_Length = iris_data['Sepal.Length'].astype(float)
Sepal_Length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [85]:
# 排序：将数值从小到大排列
np.sort(Sepal_Length)

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [86]:
# 去重：提取数组中所有不重复的数值
np.unique(Sepal_Length)

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

In [87]:
# 求和：计算数组中所有数值的总和
np.sum(Sepal_Length)

np.float64(876.5)

In [88]:
# 累积和：返回一个数组，每个元素是前面所有元素的总和
np.cumsum(Sepal_Length)

array([  5.1,  10. ,  14.7,  19.3,  24.3,  29.7,  34.3,  39.3,  43.7,
        48.6,  54. ,  58.8,  63.6,  67.9,  73.7,  79.4,  84.8,  89.9,
        95.6, 100.7, 106.1, 111.2, 115.8, 120.9, 125.7, 130.7, 135.7,
       140.9, 146.1, 150.8, 155.6, 161. , 166.2, 171.7, 176.6, 181.6,
       187.1, 192. , 196.4, 201.5, 206.5, 211. , 215.4, 220.4, 225.5,
       230.3, 235.4, 240. , 245.3, 250.3, 257.3, 263.7, 270.6, 276.1,
       282.6, 288.3, 294.6, 299.5, 306.1, 311.3, 316.3, 322.2, 328.2,
       334.3, 339.9, 346.6, 352.2, 358. , 364.2, 369.8, 375.7, 381.8,
       388.1, 394.2, 400.6, 407.2, 414. , 420.7, 426.7, 432.4, 437.9,
       443.4, 449.2, 455.2, 460.6, 466.6, 473.3, 479.6, 485.2, 490.7,
       496.2, 502.3, 508.1, 513.1, 518.7, 524.4, 530.1, 536.3, 541.4,
       547.1, 553.4, 559.2, 566.3, 572.6, 579.1, 586.7, 591.6, 598.9,
       605.6, 612.8, 619.3, 625.7, 632.5, 638.2, 644. , 650.4, 656.9,
       664.6, 672.3, 678.3, 685.2, 690.8, 698.5, 704.8, 711.5, 718.7,
       724.9, 731. ,

In [89]:
# 均值：计算平均数
np.mean(Sepal_Length)

np.float64(5.843333333333334)

In [90]:
# 标准差：反映数据的离散程度（数值越小说明数据越集中）
np.std(Sepal_Length)

np.float64(0.8253012917851409)

In [91]:
# 方差：标准差的平方
np.var(Sepal_Length)

np.float64(0.6811222222222223)